### ISSUE TITLE
RowsCopied is 0

### ISSUE THREAD

**Issue by efurban** [corelevel/DatabaseArchiving#1]
Hi, 

I came across your script and love it. however, after setup the run, the RowCopid is always 0. 
Also, the KeyMaxValue always equals LastArchivedKey.  
Any help would be really appreciated. thanks. 

![image](https://user-images.githubusercontent.com/3455707/180568082-31bdd8dc-139c-4174-a513-a49982b6b360.png)
![image](https://user-images.githubusercontent.com/3455707/180568180-4c9b4c69-62ef-442e-95d3-ee779316d21c.png)

**Comment by corelevel** [comment]
Hey!
I just updated my script with the latest version. But there are no major changes.
You should remove a database name from _KeyQuery_: instead of _OwsOperations.dbo.tbl_gmiv..._ use just _dbo.tbl_gmiv..._ 
Because it used multiple times for different databases, but in your case it will always return the same result.
Let me know if that will not help

**Comment by efurban** [comment]
All is working now. thank you!

**Comment by corelevel** [comment]
Cool
